(ImageProcessing) Adds intensity_histogram
robstewart57/orc-apps pull request #8
Opened 2017-02-08 13:05 UTC by cajturner

This MR adds the intensity histogram actor. The actor expects a stream of pixels with values between 0-255. An array of occurrences for each value is created and once the whole image has been consumed, the array is streamed out of the actor from 0-255. The image size is calculated from the constants.

@RossBrunton @Teymoor-Ali @VincentDawn Could someone please review?

FYI @robstewart57 @KirstyRD

2017-02-08 18:44 UTC, RossBrunton requested changes
Sorry in advance for the tone in any of these, I've not done many code reviews. The logic in the actor seems fine, however, it's just me nitpicking! :D

2017-02-08 18:44 UTC, RossBrunton commented on ImageProcessing/src/image/image_processing/intensity_histogram.cal
> +    uint(size=32) p_count := 0;
You seem to be mixing spaces and tabs, which is a pain for some editors to handle, and results in viewers which use different sizes for tabs and spaces to not align properly.

2017-02-08 18:44 UTC, RossBrunton commented on ImageProcessing/src/image/image_processing/intensity_histogram.cal
> +	println("init "+i);
Debugging print statement left in.

2017-02-08 18:44 UTC, RossBrunton commented on ImageProcessing/src/image/image_processing/intensity_histogram.cal
> +	initDone: action ==>
Is this just to zero out the array? If so, I think doing this using states like this is a bit messy.

I think `[0: for uint(size=32) _ in 1 .. (IM_WIDTH_OUT * IM_HEIGHT_OUT * COLOUR_CHANNELS_OUT)]` looks clearer, but maybe that's me. @robstewart57 what's the best way of doing this?

2017-02-08 18:44 UTC, RossBrunton commented on ImageProcessing/src/image/image_processing/intensity_histogram.cal
> +    guard
Perhaps using states for this rather than guards would be better?

That is, an "init" state, a "process" state and an "output" state.

2017-02-08 18:44 UTC, RossBrunton commented on ImageProcessing/src/image/image_processing/intensity_histogram.cal
> +end
Files should have newlines at the end of them.

Yes, I'm petty.

2017-02-08 18:47 UTC, RossBrunton submitted a review, later dismissed

2017-02-08 18:47 UTC, RossBrunton commented on ImageProcessing/src/image/image_processing/intensity_histogram.cal
> +	uint(size=8) histogram [255] := [0];
This should be a 256 element array, not a 255 element one.

2017-02-09 10:21 UTC, cajturner commented
Hi @robstewart57, Thanks for your review! These are fantastic comments and exactly what I need. Please be as detailed as possible as it is very useful. I will update the PR

2017-02-09 14:10 UTC, robstewart57 commented
@cajturner These weren't my comments. Rather, @RossBrunton 's comments.

2017-02-09 14:34 UTC, cajturner commented
Opps, Sorry meant @RossBrunton.

2017-02-13 00:30 UTC, robstewart57 commented
@cajturner I'm not to merge this yet, right?

2017-02-14 09:28 UTC, cajturner commented
@robstewart57 Please do not merge this yet, I still need to make changes

2017-03-21 13:23 UTC, cajturner commented
Appoligies all for the delay.
@RossBrunton I think I have addressed all of your comments. Could you have a last check over? Cheers!

2017-03-27 17:20 UTC, RossBrunton approved these changes
Ship it!

2017-03-27 19:31 UTC, merged

2017-03-27 19:31 UTC, robstewart57 commented
Squashed and merged.